### ISSUE TITLE
No work on 3.5.6

### ISSUE THREAD

**Issue by piyushbest** [FaigerSYS/MapImageEngine#53]
7.75% von 512 MB RAM  10% SSD 0 0 -1 1 2 3 4 5 6 7 8 9 10 11 10% von 512 MB Speicherplatz     HyperPe@UTK-Gamer-Mini-Games:~/server [13:00:17] [Server thread/DEBUG]: #1 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/MapImageEngine(74): FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::checkCompatiblity() [13:00:17] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(123): FaigerSYS\MapImageEngine\MapImageEngine->onEnable() [13:00:17] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1) [13:00:17] [Server thread/DEBUG]: #4 src/pocketmine/Server(2001): pocketmine\plugin\PluginManager->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object) [13:00:17] [Server thread/DEBUG]: #5 src/pocketmine/Server(1987): pocketmine\Server->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object) [13:00:17] [Server thread/DEBUG]: #6 src/pocketmine/Server(1781): pocketmine\Server->enablePlugins(integer 1) [13:00:17] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/) [13:00:17] [Server thread/DEBUG]: #8 (1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php) [13:00:17] [Server thread/INFO]: Disabling MapImageEngine v1.1.1 [13:00:17] [Server thread/INFO]: Enabling AutoInv v0.0.10 [13:00:17] [Server thread/INFO]: Enabling Worlds v2.0.3 [13:00:17] [Server thread/INFO]: Enabling WarpUI v1.2 [13:00:17] [Server thread/INFO]: Enabling PurePerms v1.4.2 [13:00:17] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1. [13:00:17] [Server thread/INFO]: Enabling MIE_Converter v1.0.2 [13:00:17] [Server thread/INFO]: [MIE_Converter] MIE_Converter enabling... [13:00:17] [Server thread/INFO]: [MIE_Converter] MIE_Converter enabled! MIEI version: 2 [13:00:17] [Server thread/INFO]: Enabling EconomyAPI v5.7.3 [13:00:18] [Server thread/NOTICE]: [EconomyAPI] [13:00:18] [Server thread/NOTICE]: [EconomyAPI] Database provider was set to: Yaml [13:00:18] [Server thread/INFO]: Enabling PureChat v1.4.11 [13:00:18] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support. [13:00:18] [Server thread/INFO]: Starting GS4 status listener [13:00:18] [Server thread/INFO]: Setting query port to 25888 [13:00:18] [Server thread/INFO]: Query running on 0.0.0.0:25888 [13:00:18] [Server thread/INFO]: Default game type: Survival Mode [13:00:18] [Server thread/INFO]: Done (1.197s)! For help, type "help" or "?" [13:00:20] [Server thread/INFO]: [SkyWars] Started to load arenas worlds... [13:00:20] [Server thread/INFO]: Preparing level "end" [13:00:20] [Server thread/INFO]: Preparing level "SkyWarsForPE" [13:01:11] [Server thread/INFO]: PiyushBest[/47.247.212.165:55491] logged in with entity id 1 at (world, 328.0005, 225, 173.0346) [13:01:24] [Server thread/INFO]: PiyushBest joined the game [13:02:33] [Server thread/INFO]: PiyushBest left the game [13:02:33] [Server thread/INFO]: PiyushBest[/47.247.212.165:55491] logged out due to timeout [13:02:50] [Server thread/INFO]: [CONSOLE: Saving...] [13:02:50] [Server thread/INFO]: [CONSOLE: Saved the world] --------------------------------------- Minecraft Server wird gestartet... Gestartet am: 25.01.2019 um 12:02:57 Uhr Server-Software: POCKETMINE Server-Version: LATEST RAM: 512 MB --------------------------------------- [13:02:57] [Server thread/INFO]: Loading pocketmine.yml... [13:02:57] [Server thread/INFO]: Loading server properties... [13:02:57] [Server thread/INFO]: Selected English (eng) as the base language [13:02:57] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.8.0 [13:02:57] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live. [13:02:57] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties. [13:02:57] [Server thread/INFO]: Opening server on 0.0.0.0:25888 [13:02:57] [Server thread/INFO]: This server is running PocketMine-MP version 3.5.6 [13:02:57] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License [13:02:57] [Server thread/INFO]: Loading resource packs... [13:02:57] [Server thread/INFO]: Loading SkyWarsForPE v1.9.2 Xandrine [13:02:57] [Server thread/INFO]: [SkyWars] Loaded SkyWars configuration into system. [13:02:57] [Server thread/INFO]: [SkyWars] Tracked and flashed 2 locales [13:02:57] [Server thread/INFO]: [SkyWars] Successfully loaded the sqlite driver [13:02:57] [Server thread/INFO]: Loading MIE_Protector v1.0.4 [13:02:57] [Server thread/INFO]: Loading Slapper v1.4.2 [13:02:57] [Server thread/INFO]: Loading MapImageEngine v1.1.1 [13:02:57] [Server thread/INFO]: Loading AutoInv v0.0.10 [13:02:57] [Server thread/INFO]: Loading Worlds v2.0.3 [13:02:57] [Server thread/INFO]: Loading WarpUI v1.2 [13:02:57] [Server thread/INFO]: Loading TeaSpoon v1.0.1 [13:02:57] [Server thread/INFO]: [TeaSpoon] Loading Resources... [13:02:57] [Server thread/INFO]: Loading PurePerms v1.4.2 [13:02:57] [Server thread/NOTICE]: PurePerms by 64FF00 & ProjectInfinity! #LEET.CC 888 888 .d8888b. d8888 8888888888 8888888888 .d8888b. .d8888b. 888 888 d88P Y88b d8P888 888 888 d88P Y88b d88P Y88b 888888888888 888 d8P 888 888 888 888 888 888 888 888 888 888d888b. d8P 888 8888888 8888888 888 888 888 888 888 888 888P "Y88b d88 888 888 888 888 888 888 888 888888888888 888 888 8888888888 888 888 888 888 888 888 888 888 Y88b d88P 888 888 888 Y88b d88P Y88b d88P 888 888 "Y8888P" 888 888 888 "Y8888P" "Y8888P" [13:02:57] [Server thread/INFO]: [PurePerms] Setting default language to 'en' [13:02:57] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled. [13:02:57] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions! [13:02:57] [Server thread/INFO]: Loading MIE_Converter v1.0.2 [13:02:57] [Server thread/INFO]: Loading EconomyAPI v5.7.3 [13:02:57] [Server thread/INFO]: Loading PureChat v1.4.11 [13:02:57] [Server thread/INFO]: Enabling TeaSpoon v1.0.1 [13:02:57] [Server thread/INFO]: [TeaSpoon] Loading... MMP""MM""YMM .M"""bgd P' MM `7 ,MI "Y MM .gP"Ya ,6"Yb. `MMb. `7MMpdMAo. ,pW"Wq. ,pW"Wq.`7MMpMMMb. MM ,M' Yb 8) MM `YMMNq. MM `Wb 6W' `Wb 6W' `Wb MM MM MM 8M"""""" ,pm9MM . `MM MM M8 8M M8 8M M8 MM MM MM YM. , 8M MM Mb dM MM ,AP YA. ,A9 YA. ,A9 MM MM .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd" MMbmmd' `Ybmd9' `Ybmd9'.JMML JMML. MM .JMML. @TheAz928 is notorious for HardCoding values! Copyright (C) CortexPE 2017-2019 [13:02:57] [Server thread/INFO]: [TeaSpoon] TeaSpoon is distributed under the AGPL License [13:02:57] [Server thread/INFO]: Preparing level "world" [13:02:57] [Server thread/INFO]: Preparing level "teanether" [13:02:57] [Server thread/INFO]: Preparing level "ender" [13:02:57] [Server thread/INFO]: Enabling SkyWarsForPE v1.9.2 Xandrine [13:02:57] [Server thread/INFO]: [SkyWars] Starting SkyWarsForPE modules... [13:02:57] [Server thread/INFO]: [SkyWars] Loaded chest random configuration. [13:02:57] [Server thread/INFO]: [SkyWars] Locating arena files... [13:02:58] [Server thread/INFO]: Preparing level "SW" [13:02:58] [Server thread/INFO]: [SkyWars] End - Arena loaded and enabled [13:02:58] [Server thread/INFO]: [SkyWars] Default - Arena disabled [13:02:58] [Server thread/INFO]: [SkyWars] SkyWarsForPE has been enabled [13:02:58] [Server thread/INFO]: Enabling MIE_Protector v1.0.4 [13:02:58] [Server thread/INFO]: [MIE_Protector] MIE_Protector enabling... [13:02:58] [Server thread/INFO]: [MIE_Protector] MIE_Protector enabled! [13:02:58] [Server thread/INFO]: Enabling Slapper v1.4.2 [13:02:58] [Server thread/INFO]: Enabling MapImageEngine v1.1.1 [13:02:58] [Server thread/INFO]: [MapImageEngine] MapImageEngine enabling... [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #1: find the instructions in the plugin folder [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #2: after installing new images or updating plugin enabling may take longer, but then it will be as usual [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #3: after installing MapImageEngine v1.1 you must place all your previously placed images again [13:02:58] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\ClientboundMapItemDataPacket::$decorationEntityUniqueIds" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164 [13:02:58] [Server thread/DEBUG]: #0 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/packet/CustomClientboundMapItemDataPacket(208): pocketmine\network\mcpe\protocol\DataPacket->__set(string decorationEntityUniqueIds, array Array()) [13:02:58] [Server thread/DEBUG]: #1 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/MapImageEngine(74): FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::checkCompatiblity() [13:02:58] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(123): FaigerSYS\MapImageEngine\MapImageEngine->onEnable() [13:02:58] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\Plug

**Comment by nikipuh** [comment]
`7.75% von 512 MB RAM 10% SSD 0 0 -1 1 2 3 4 5 6 7 8 9 10 11 10% von 512 MB Speicherplatz HyperPe@UTK-Gamer-Mini-Games:~/server [13:00:17] [Server thread/DEBUG]: #1 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/MapImageEngine(74): FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::checkCompatiblity() [13:00:17] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(123): FaigerSYS\MapImageEngine\MapImageEngine->onEnable() [13:00:17] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1) [13:00:17] [Server thread/DEBUG]: #4 src/pocketmine/Server(2001): pocketmine\plugin\PluginManager->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object) [13:00:17] [Server thread/DEBUG]: #5 src/pocketmine/Server(1987): pocketmine\Server->enablePlugin(FaigerSYS\MapImageEngine\MapImageEngine object) [13:00:17] [Server thread/DEBUG]: #6 src/pocketmine/Server(1781): pocketmine\Server->enablePlugins(integer 1) [13:00:17] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/) [13:00:17] [Server thread/DEBUG]: #8 (1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php) [13:00:17] [Server thread/INFO]: Disabling MapImageEngine v1.1.1 [13:00:17] [Server thread/INFO]: Enabling AutoInv v0.0.10 [13:00:17] [Server thread/INFO]: Enabling Worlds v2.0.3 [13:00:17] [Server thread/INFO]: Enabling WarpUI v1.2 [13:00:17] [Server thread/INFO]: Enabling PurePerms v1.4.2 [13:00:17] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1. [13:00:17] [Server thread/INFO]: Enabling MIE_Converter v1.0.2 [13:00:17] [Server thread/INFO]: [MIE_Converter] MIE_Converter enabling... [13:00:17] [Server thread/INFO]: [MIE_Converter] MIE_Converter enabled! MIEI version: 2 [13:00:17] [Server thread/INFO]: Enabling EconomyAPI v5.7.3 [13:00:18] [Server thread/NOTICE]: [EconomyAPI] [13:00:18] [Server thread/NOTICE]: [EconomyAPI] Database provider was set to: Yaml [13:00:18] [Server thread/INFO]: Enabling PureChat v1.4.11 [13:00:18] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support. [13:00:18] [Server thread/INFO]: Starting GS4 status listener [13:00:18] [Server thread/INFO]: Setting query port to 25888 [13:00:18] [Server thread/INFO]: Query running on 0.0.0.0:25888 [13:00:18] [Server thread/INFO]: Default game type: Survival Mode [13:00:18] [Server thread/INFO]: Done (1.197s)! For help, type "help" or "?" [13:00:20] [Server thread/INFO]: [SkyWars] Started to load arenas worlds... [13:00:20] [Server thread/INFO]: Preparing level "end" [13:00:20] [Server thread/INFO]: Preparing level "SkyWarsForPE" [13:01:11] [Server thread/INFO]: PiyushBest[/47.247.212.165:55491] logged in with entity id 1 at (world, 328.0005, 225, 173.0346) [13:01:24] [Server thread/INFO]: PiyushBest joined the game [13:02:33] [Server thread/INFO]: PiyushBest left the game [13:02:33] [Server thread/INFO]: PiyushBest[/47.247.212.165:55491] logged out due to timeout [13:02:50] [Server thread/INFO]: [CONSOLE: Saving...] [13:02:50] [Server thread/INFO]: [CONSOLE: Saved the world] --------------------------------------- Minecraft Server wird gestartet... Gestartet am: 25.01.2019 um 12:02:57 Uhr Server-Software: POCKETMINE Server-Version: LATEST RAM: 512 MB --------------------------------------- [13:02:57] [Server thread/INFO]: Loading pocketmine.yml... [13:02:57] [Server thread/INFO]: Loading server properties... [13:02:57] [Server thread/INFO]: Selected English (eng) as the base language [13:02:57] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.8.0 [13:02:57] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live. [13:02:57] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties. [13:02:57] [Server thread/INFO]: Opening server on 0.0.0.0:25888 [13:02:57] [Server thread/INFO]: This server is running PocketMine-MP version 3.5.6 [13:02:57] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License [13:02:57] [Server thread/INFO]: Loading resource packs... [13:02:57] [Server thread/INFO]: Loading SkyWarsForPE v1.9.2 Xandrine [13:02:57] [Server thread/INFO]: [SkyWars] Loaded SkyWars configuration into system. [13:02:57] [Server thread/INFO]: [SkyWars] Tracked and flashed 2 locales [13:02:57] [Server thread/INFO]: [SkyWars] Successfully loaded the sqlite driver [13:02:57] [Server thread/INFO]: Loading MIE_Protector v1.0.4 [13:02:57] [Server thread/INFO]: Loading Slapper v1.4.2 [13:02:57] [Server thread/INFO]: Loading MapImageEngine v1.1.1 [13:02:57] [Server thread/INFO]: Loading AutoInv v0.0.10 [13:02:57] [Server thread/INFO]: Loading Worlds v2.0.3 [13:02:57] [Server thread/INFO]: Loading WarpUI v1.2 [13:02:57] [Server thread/INFO]: Loading TeaSpoon v1.0.1 [13:02:57] [Server thread/INFO]: [TeaSpoon] Loading Resources... [13:02:57] [Server thread/INFO]: Loading PurePerms v1.4.2 [13:02:57] [Server thread/NOTICE]: PurePerms by 64FF00 & ProjectInfinity! #LEET.CC 888 888 .d8888b. d8888 8888888888 8888888888 .d8888b. .d8888b. 888 888 d88P Y88b d8P888 888 888 d88P Y88b d88P Y88b 888888888888 888 d8P 888 888 888 888 888 888 888 888 888 888d888b. d8P 888 8888888 8888888 888 888 888 888 888 888 888P "Y88b d88 888 888 888 888 888 888 888 888888888888 888 888 8888888888 888 888 888 888 888 888 888 888 Y88b d88P 888 888 888 Y88b d88P Y88b d88P 888 888 "Y8888P" 888 888 888 "Y8888P" "Y8888P" [13:02:57] [Server thread/INFO]: [PurePerms] Setting default language to 'en' [13:02:57] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled. [13:02:57] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions! [13:02:57] [Server thread/INFO]: Loading MIE_Converter v1.0.2 [13:02:57] [Server thread/INFO]: Loading EconomyAPI v5.7.3 [13:02:57] [Server thread/INFO]: Loading PureChat v1.4.11 [13:02:57] [Server thread/INFO]: Enabling TeaSpoon v1.0.1 [13:02:57] [Server thread/INFO]: [TeaSpoon] Loading... MMP""MM""YMM .M"""bgd P' MM 7 ,MI "Y MM .gP"Ya ,6"Yb. MMb. 7MMpdMAo. ,pW"Wq. ,pW"Wq.7MMpMMMb. MM ,M' Yb 8) MM YMMNq. MM Wb 6W' Wb 6W' Wb MM MM MM 8M"""""" ,pm9MM . MM MM M8 8M M8 8M M8 MM MM MM YM. , 8M MM Mb dM MM ,AP YA. ,A9 YA. ,A9 MM MM .JMML.Mbmmd' Moo9^Yo.P"Ybmmd" MMbmmd' Ybmd9' `Ybmd9'.JMML JMML. MM .JMML. @TheAz928 is notorious for HardCoding values! Copyright (C) CortexPE 2017-2019 [13:02:57] [Server thread/INFO]: [TeaSpoon] TeaSpoon is distributed under the AGPL License [13:02:57] [Server thread/INFO]: Preparing level "world" [13:02:57] [Server thread/INFO]: Preparing level "teanether" [13:02:57] [Server thread/INFO]: Preparing level "ender" [13:02:57] [Server thread/INFO]: Enabling SkyWarsForPE v1.9.2 Xandrine [13:02:57] [Server thread/INFO]: [SkyWars] Starting SkyWarsForPE modules... [13:02:57] [Server thread/INFO]: [SkyWars] Loaded chest random configuration. [13:02:57] [Server thread/INFO]: [SkyWars] Locating arena files... [13:02:58] [Server thread/INFO]: Preparing level "SW" [13:02:58] [Server thread/INFO]: [SkyWars] End - Arena loaded and enabled [13:02:58] [Server thread/INFO]: [SkyWars] Default - Arena disabled [13:02:58] [Server thread/INFO]: [SkyWars] SkyWarsForPE has been enabled [13:02:58] [Server thread/INFO]: Enabling MIE_Protector v1.0.4 [13:02:58] [Server thread/INFO]: [MIE_Protector] MIE_Protector enabling... [13:02:58] [Server thread/INFO]: [MIE_Protector] MIE_Protector enabled! [13:02:58] [Server thread/INFO]: Enabling Slapper v1.4.2 [13:02:58] [Server thread/INFO]: Enabling MapImageEngine v1.1.1 [13:02:58] [Server thread/INFO]: [MapImageEngine] MapImageEngine enabling... [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #1: find the instructions in the plugin folder [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #2: after installing new images or updating plugin enabling may take longer, but then it will be as usual [13:02:58] [Server thread/INFO]: [MapImageEngine] Notice #3: after installing MapImageEngine v1.1 you must place all your previously placed images again [13:02:58] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\ClientboundMapItemDataPacket::$decorationEntityUniqueIds" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164 [13:02:58] [Server thread/DEBUG]: #0 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/packet/CustomClientboundMapItemDataPacket(208): pocketmine\network\mcpe\protocol\DataPacket->__set(string decorationEntityUniqueIds, array Array()) [13:02:58] [Server thread/DEBUG]: #1 plugins/MapImageEngine_dev-22.phar/src/FaigerSYS/MapImageEngine/MapImageEngine(74): FaigerSYS\MapImageEngine\packet\CustomClientboundMapItemDataPacket::checkCompatiblity() [13:02:58] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(123): FaigerSYS\MapImageEngine\MapImageEngine->onEnable() [13:02:58] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\Plug`
