### ISSUE TITLE
warning message running PocketMine-MP version 3.8.0

### ISSUE THREAD

**Issue by teracube** [FaigerSYS/MapImageEngine#56]
https://poggit.pmmp.io/r/46961/MapImageEngine_dev-23.phar
https://github.com/pmmp/PocketMine-MP/releases/tag/3.8.0

[Server thread/WARNING]: [MapImageEngine] It seems our custom packet for caching support is incompatible with your server software. Loading images may be slower than usual

no message running PMMP 3.7.3 older version

what is the problem
thanks

**Comment by JUSTaMod** [comment]
This is due to the 1.11.0 protocol changes made in [this commit](https://github.com/pmmp/PocketMine-MP/commit/fa70127241db2068915328365b6c98a862271783#diff-f788298f701201ca3f1f06eeedbabee8).

I've fixed the issue in [this phar](https://snowridge.tk/subpages/PMMP/assets/MapImageEngine_v1.1.3.phar).

And to cover my butt-
The author of this plugin does not condone the use of the phar provided.
Please make a backup of your server before use.

**Comment by teracube** [comment]
@JUSTaMod 
@FaigerSYS 

same issue running PMMP 3.8.4

https://poggit.pmmp.io/r/46961/MapImageEngine_dev-23.phar
https://jenkins.pmmp.io/job/PocketMine-MP/1765/artifact/PocketMine-MP.phar

019-06-15 [07:10:04] [Server thread/WARNING]: [MapImageEngine] It seems our custom packet for caching support is incompatible with your server software. Loading images may be slower than usual

**Comment by JUSTaMod** [comment]
Correct. This plugin has not been officially updated in 7+ months. You will continue to receive that message.
